pipeline{
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ACCOUNT_ID = "720035686659"
        ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-project"
        IMAGE_TAG = "${BUILD_NUMBER}"
        SONAR_SERVER = "sonar-server"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/priyankatanneru/java-project.git'
            }
        }

        stage('Build (Maven)') {
            steps {
                dir('app'){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_AUTH_TOKEN')]) {
                            sh """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=devops-project \
                            -Dsonar.login=$SONAR_AUTH_TOKEN
                            """
                        }
                    }
                }
            }
        }

        stage('Quality Gate'){
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
           }
        }

        stage('Build Docker Image') {
            steps {
                dir('app'){
                    sh """
                    docker build -t devops-project .
                    docker tag devops-project:latest $ECR_REPO:$IMAGE_TAG
                    """
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh "docker push $ECR_REPO:$IMAGE_TAG"
            }
        }
        
        stage('Update K8s Manifest (GitOps)') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_PASS')]) {
                    sh '''
                        git config --global user.email "jenkins@example.com"
                        git config --global user.name "Jenkins CI"
                        git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/your-org/your-repo.git
                        cd your-repo
                        # Update your K8s manifests
                        git add .
                        git commit -m "Update manifests via Jenkins pipeline"
                        git push origin main
                    '''
                }
            }
        }
                
    }
}
