pipeline{
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ACCOUNT_ID = "720035686659"
        ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-project"
        IMAGE_TAG = "${BUILD_NUMBER}"
        SONAR_SERVER = "sonar-server"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/priyankatanneru/java-project.git'
            }
        }

        stage('Build (Maven)') {
            steps {
                dir('app'){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_AUTH_TOKEN')]) {
                            sh """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=devops-project \
                            -Dsonar.login=$SONAR_AUTH_TOKEN
                            """
                        }
                    }
                }
            }
        }

        stage('Quality Gate'){
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
           }
        }

        stage('Build Docker Image') {
            steps {
                dir('app'){
                    sh """
                    docker build -t devops-project .
                    docker tag devops-project:latest $ECR_REPO:$IMAGE_TAG
                    """
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh "docker push $ECR_REPO:$IMAGE_TAG"
            }
        }
        stage('Update K8s Manifest (GitOps)') {
            when {
                branch 'develop' // Only run on develop branch
            }
            steps {
                // Bind your GitHub token stored in Jenkins credentials
                withCredentials([string(credentialsId: 'github-creds', variable: 'GITHUB_TOKEN')]) {
                    sh """
                    # Update the image in deployment.yaml with the new ECR image tag
                    sed -i "s|image:.*|image: $ECR_REPO:$IMAGE_TAG|" k8s-manifests/deployment.yaml
        
                    # Configure Git user
                    git config --global user.name "jenkins"
                    git config --global user.email "jenkins@example.com"
        
                    # Add changes
                    git add k8s-manifests/deployment.yaml
        
                    # Commit changes (if any)
                    git commit -m "Update image to $IMAGE_TAG" || echo "No changes to commit"
        
                    # Push changes to GitHub using token
                    git push https://priyankatanneru:$GITHUB_TOKEN@github.com/priyankatanneru/java-project.git HEAD:develop
                    """
                }
            }
        }
        
    }
}
